# THIS IS NOT HOW YOU SHOULD DO DEPLOYMENTS FOR YOUR ORGANIZATION
#
# First off, the sed stuff for modifying import maps is quite hacky and shouldn't
# be what you rely on.
#
# Secondly, each angular app should be in a separate repo and deployed separately, as
# explained in the README.md.
language: node_js
node_js:
  - "node"
script:
  - cd navbar && npm ci && ng build --prod --output-hashing none
  - cd ../app1 && npm ci && ng build --prod --output-hashing none
  - cd ../app2 && npm ci && ng build --prod --output-hashing none
  - cd .. && mkdir static && cp -a navbar/dist app1/dist app2/dist static
  - cp root-html-file/index.html static
  - sed -i 's/http:\/\/localhost:4201/\/dist\/app1/g' static/index.html
  - sed -i 's/http:\/\/localhost:4202/\/dist\/app2/g' static/index.html
  - sed -i 's/http:\/\/localhost:4203/\/dist\/app3/g' static/index.html
  - cp static/index.html static/200.html
deploy:
  provider: surge
  project: ./static/
  domain: coexisting-angular-microfrontends.surge.sh
  skip_cleanup: true